runtime: python39

env_variables:
  OPENAI_API_KEY: "your OpenAI API key"
  GCP_PROJECT_ID: "your GCP project ID"
  FIRESTORE_DB: "your Firestore database name"

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto

service: test